# Generated by Django 4.1.3 on 2023-04-04 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_summary_generated_date_alter_summary_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='generated_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
