# Generated by Django 4.1.3 on 2023-04-04 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_summary_generated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.userprofile'),
        ),
    ]
